# coding: utf-8

"""
    Model Catalog

    This is the API of the  Software Description Ontology at [https://mintproject.github.io/Mint-ModelCatalog-Ontology/release/1.2.0/index-en.html](https://w3id.org/okn/o/sdm)  # noqa: E501

    OpenAPI spec version: v1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.models.farming_practices import FarmingPractices  # noqa: E501
from modelcatalog.rest import ApiException


class TestFarmingPractices(unittest.TestCase):
    """FarmingPractices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFarmingPractices(self):
        """Test FarmingPractices"""
        # FIXME: construct object with mandatory attributes with example values
        # model = modelcatalog.models.farming_practices.FarmingPractices()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
