# coding: utf-8

"""
    Model Catalog

    This is MINT Model Catalog You can find out more about Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)  # noqa: E501

    OpenAPI spec version: v1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.model_configuration_api import ModelConfigurationApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestModelConfigurationApi(unittest.TestCase):
    """ModelConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.model_configuration_api.ModelConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_modelconfigurations_get(self):
        """Test case for modelconfigurations_get

        List all ModelConfiguration entities  # noqa: E501
        """
        pass

    def test_modelconfigurations_id_delete(self):
        """Test case for modelconfigurations_id_delete

        Delete a ModelConfiguration  # noqa: E501
        """
        pass

    def test_modelconfigurations_id_get(self):
        """Test case for modelconfigurations_id_get

        Get a ModelConfiguration  # noqa: E501
        """
        pass

    def test_modelconfigurations_id_put(self):
        """Test case for modelconfigurations_id_put

        Update a ModelConfiguration  # noqa: E501
        """
        pass

    def test_modelconfigurations_post(self):
        """Test case for modelconfigurations_post

        Create a ModelConfiguration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
