# coding: utf-8

"""
    Model Catalog

    This is MINT Model Catalog You can find out more about Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)  # noqa: E501

    OpenAPI spec version: v1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.models.funding_information import FundingInformation  # noqa: E501
from modelcatalog.rest import ApiException


class TestFundingInformation(unittest.TestCase):
    """FundingInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFundingInformation(self):
        """Test FundingInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = modelcatalog.models.funding_information.FundingInformation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
