# coding: utf-8

"""
    Model Catalog

    This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.equation_api import EquationApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestEquationApi(unittest.TestCase):
    """EquationApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.equation_api.EquationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_equations_get(self):
        """Test case for equations_get

        List all instances of Equation  # noqa: E501
        """
        pass

    def test_equations_id_delete(self):
        """Test case for equations_id_delete

        Delete an existing Equation  # noqa: E501
        """
        pass

    def test_equations_id_get(self):
        """Test case for equations_id_get

        Get a single Equation by its id  # noqa: E501
        """
        pass

    def test_equations_id_put(self):
        """Test case for equations_id_put

        Update an existing Equation  # noqa: E501
        """
        pass

    def test_equations_post(self):
        """Test case for equations_post

        Create one Equation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
