# coding: utf-8

"""
    Model Catalog

    This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: mosorio@isi.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mint_client
from mint_client.api.variablespresentations_api import VariablespresentationsApi  # noqa: E501
from mint_client.rest import ApiException


class TestVariablespresentationsApi(unittest.TestCase):
    """VariablespresentationsApi unit test stubs"""

    def setUp(self):
        self.api = mint_client.api.variablespresentations_api.VariablespresentationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_datasetspecification_id_variablepresentations_get(self):
        """Test case for datasetspecification_id_variablepresentations_get

        List variable presentations related with a datasetspecification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
