# coding: utf-8

"""
    Model Catalog

    This is MINT Model Catalog You can find out more about Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)  # noqa: E501

    OpenAPI spec version: v1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.hybrid_model_api import HybridModelApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestHybridModelApi(unittest.TestCase):
    """HybridModelApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.hybrid_model_api.HybridModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hybridmodels_get(self):
        """Test case for hybridmodels_get

        List all HybridModel entities  # noqa: E501
        """
        pass

    def test_hybridmodels_id_delete(self):
        """Test case for hybridmodels_id_delete

        Delete a HybridModel  # noqa: E501
        """
        pass

    def test_hybridmodels_id_get(self):
        """Test case for hybridmodels_id_get

        Get a HybridModel  # noqa: E501
        """
        pass

    def test_hybridmodels_id_put(self):
        """Test case for hybridmodels_id_put

        Update a HybridModel  # noqa: E501
        """
        pass

    def test_hybridmodels_post(self):
        """Test case for hybridmodels_post

        Create a HybridModel  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
