# coding: utf-8

"""
    Model Catalog

    This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.software_api import SoftwareApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestSoftwareApi(unittest.TestCase):
    """SoftwareApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.software_api.SoftwareApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_softwares_get(self):
        """Test case for softwares_get

        List all instances of Software  # noqa: E501
        """
        pass

    def test_softwares_id_delete(self):
        """Test case for softwares_id_delete

        Delete an existing Software  # noqa: E501
        """
        pass

    def test_softwares_id_get(self):
        """Test case for softwares_id_get

        Get a single Software by its id  # noqa: E501
        """
        pass

    def test_softwares_id_put(self):
        """Test case for softwares_id_put

        Update an existing Software  # noqa: E501
        """
        pass

    def test_softwares_post(self):
        """Test case for softwares_post

        Create one Software  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
