# coding: utf-8

"""
    Model Catalog

    This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.model_configuration_api import ModelConfigurationApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestModelConfigurationApi(unittest.TestCase):
    """ModelConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.model_configuration_api.ModelConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_custom_modelconfigurations_id_get(self):
        """Test case for custom_modelconfigurations_id_get

        Get a ModelConfiguration  # noqa: E501
        """
        pass

    def test_modelconfigurations_get(self):
        """Test case for modelconfigurations_get

        List all instances of ModelConfiguration  # noqa: E501
        """
        pass

    def test_modelconfigurations_id_delete(self):
        """Test case for modelconfigurations_id_delete

        Delete an existing ModelConfiguration  # noqa: E501
        """
        pass

    def test_modelconfigurations_id_get(self):
        """Test case for modelconfigurations_id_get

        Get a single ModelConfiguration by its id  # noqa: E501
        """
        pass

    def test_modelconfigurations_id_put(self):
        """Test case for modelconfigurations_id_put

        Update an existing ModelConfiguration  # noqa: E501
        """
        pass

    def test_modelconfigurations_post(self):
        """Test case for modelconfigurations_post

        Create one ModelConfiguration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
