# coding: utf-8

"""
    Model Catalog

    This is MINT Model Catalog You can find out more about Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)  # noqa: E501

    OpenAPI spec version: v1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.process_api import ProcessApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestProcessApi(unittest.TestCase):
    """ProcessApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.process_api.ProcessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_processs_get(self):
        """Test case for processs_get

        List all Process entities  # noqa: E501
        """
        pass

    def test_processs_id_delete(self):
        """Test case for processs_id_delete

        Delete a Process  # noqa: E501
        """
        pass

    def test_processs_id_get(self):
        """Test case for processs_id_get

        Get a Process  # noqa: E501
        """
        pass

    def test_processs_id_put(self):
        """Test case for processs_id_put

        Update a Process  # noqa: E501
        """
        pass

    def test_processs_post(self):
        """Test case for processs_post

        Create a Process  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
