# coding: utf-8

"""
    Model Catalog

    This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.default_api import DefaultApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_login_post(self):
        """Test case for user_login_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
