# coding: utf-8

"""
    Model Catalog

    This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.models.theory_guided_model import TheoryGuidedModel  # noqa: E501
from modelcatalog.rest import ApiException


class TestTheoryGuidedModel(unittest.TestCase):
    """TheoryGuidedModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTheoryGuidedModel(self):
        """Test TheoryGuidedModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = modelcatalog.models.theory_guided_model.TheoryGuidedModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
