# coding: utf-8

"""
    Model Catalog

    This is MINT Model Catalog You can find out more about Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)  # noqa: E501

    OpenAPI spec version: v1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.variable_api import VariableApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestVariableApi(unittest.TestCase):
    """VariableApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.variable_api.VariableApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_variables_get(self):
        """Test case for variables_get

        List all Variable entities  # noqa: E501
        """
        pass

    def test_variables_id_delete(self):
        """Test case for variables_id_delete

        Delete a Variable  # noqa: E501
        """
        pass

    def test_variables_id_get(self):
        """Test case for variables_id_get

        Get a Variable  # noqa: E501
        """
        pass

    def test_variables_id_put(self):
        """Test case for variables_id_put

        Update a Variable  # noqa: E501
        """
        pass

    def test_variables_post(self):
        """Test case for variables_post

        Create a Variable  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
