# coding: utf-8

"""
    Model Catalog

    This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: mosorio@isi.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mint_client
from mint_client.api.modelconfiguration_api import ModelconfigurationApi  # noqa: E501
from mint_client.rest import ApiException


class TestModelconfigurationApi(unittest.TestCase):
    """ModelconfigurationApi unit test stubs"""

    def setUp(self):
        self.api = mint_client.api.modelconfiguration_api.ModelconfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_inputs_by_modelconfiguration(self):
        """Test case for create_inputs_by_modelconfiguration

        Creates a new instance of a `DatasetSpecification` related as Input.  # noqa: E501
        """
        pass

    def test_create_model_configuration(self):
        """Test case for create_model_configuration

        Create a model configuration  # noqa: E501
        """
        pass

    def test_create_outputs_by_modelconfiguration(self):
        """Test case for create_outputs_by_modelconfiguration

        Create the output of a model configuration  # noqa: E501
        """
        pass

    def test_create_parameters_by_modelconfiguration(self):
        """Test case for create_parameters_by_modelconfiguration

        Create the inputs of a model configuration  # noqa: E501
        """
        pass

    def test_delete_model_configuration(self):
        """Test case for delete_model_configuration

        Delete a ModelConfiguration  # noqa: E501
        """
        pass

    def test_get_inputs_by_modelconfiguration(self):
        """Test case for get_inputs_by_modelconfiguration

        Get the inputs of a model configuration  # noqa: E501
        """
        pass

    def test_get_model_configurations(self):
        """Test case for get_model_configurations

        List modelconfiguration  # noqa: E501
        """
        pass

    def test_get_model_configuraton(self):
        """Test case for get_model_configuraton

        Get modelconfiguration  # noqa: E501
        """
        pass

    def test_get_outputs_by_modelconfiguration(self):
        """Test case for get_outputs_by_modelconfiguration

        Get the outputs of a model configuration  # noqa: E501
        """
        pass

    def test_get_parameters_by_modelconfiguration(self):
        """Test case for get_parameters_by_modelconfiguration

        Get the parameters of a model configuration  # noqa: E501
        """
        pass

    def test_update_model_configuration(self):
        """Test case for update_model_configuration

        Update model configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
