# coding: utf-8

"""
    Model Catalog

    This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.hybrid_model_api import HybridModelApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestHybridModelApi(unittest.TestCase):
    """HybridModelApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.hybrid_model_api.HybridModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hybridmodels_get(self):
        """Test case for hybridmodels_get

        List all instances of HybridModel  # noqa: E501
        """
        pass

    def test_hybridmodels_id_delete(self):
        """Test case for hybridmodels_id_delete

        Delete an existing HybridModel  # noqa: E501
        """
        pass

    def test_hybridmodels_id_get(self):
        """Test case for hybridmodels_id_get

        Get a single HybridModel by its id  # noqa: E501
        """
        pass

    def test_hybridmodels_id_put(self):
        """Test case for hybridmodels_id_put

        Update an existing HybridModel  # noqa: E501
        """
        pass

    def test_hybridmodels_post(self):
        """Test case for hybridmodels_post

        Create one HybridModel  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
