# coding: utf-8

"""
    Model Catalog

    This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.image_api import ImageApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestImageApi(unittest.TestCase):
    """ImageApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.image_api.ImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_images_get(self):
        """Test case for images_get

        List all instances of Image  # noqa: E501
        """
        pass

    def test_images_id_delete(self):
        """Test case for images_id_delete

        Delete an existing Image  # noqa: E501
        """
        pass

    def test_images_id_get(self):
        """Test case for images_id_get

        Get a single Image by its id  # noqa: E501
        """
        pass

    def test_images_id_put(self):
        """Test case for images_id_put

        Update an existing Image  # noqa: E501
        """
        pass

    def test_images_post(self):
        """Test case for images_post

        Create one Image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
