# coding: utf-8

"""
    Model Catalog

    This is MINT Model Catalog You can find out more about Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)  # noqa: E501

    OpenAPI spec version: v1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.software_version_api import SoftwareVersionApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestSoftwareVersionApi(unittest.TestCase):
    """SoftwareVersionApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.software_version_api.SoftwareVersionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_softwareversions_get(self):
        """Test case for softwareversions_get

        List all SoftwareVersion entities  # noqa: E501
        """
        pass

    def test_softwareversions_id_delete(self):
        """Test case for softwareversions_id_delete

        Delete a SoftwareVersion  # noqa: E501
        """
        pass

    def test_softwareversions_id_get(self):
        """Test case for softwareversions_id_get

        Get a SoftwareVersion  # noqa: E501
        """
        pass

    def test_softwareversions_id_put(self):
        """Test case for softwareversions_id_put

        Update a SoftwareVersion  # noqa: E501
        """
        pass

    def test_softwareversions_post(self):
        """Test case for softwareversions_post

        Create a SoftwareVersion  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
