# coding: utf-8

"""
    Model Catalog

    This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.api.parameter_api import ParameterApi  # noqa: E501
from modelcatalog.rest import ApiException


class TestParameterApi(unittest.TestCase):
    """ParameterApi unit test stubs"""

    def setUp(self):
        self.api = modelcatalog.api.parameter_api.ParameterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_parameters_get(self):
        """Test case for parameters_get

        List all instances of Parameter  # noqa: E501
        """
        pass

    def test_parameters_id_delete(self):
        """Test case for parameters_id_delete

        Delete an existing Parameter  # noqa: E501
        """
        pass

    def test_parameters_id_get(self):
        """Test case for parameters_id_get

        Get a single Parameter by its id  # noqa: E501
        """
        pass

    def test_parameters_id_put(self):
        """Test case for parameters_id_put

        Update an existing Parameter  # noqa: E501
        """
        pass

    def test_parameters_post(self):
        """Test case for parameters_post

        Create one Parameter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
