# coding: utf-8

"""
    Model Catalog

    This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import modelcatalog
from modelcatalog.models.hybrid_model import HybridModel  # noqa: E501
from modelcatalog.rest import ApiException


class TestHybridModel(unittest.TestCase):
    """HybridModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHybridModel(self):
        """Test HybridModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = modelcatalog.models.hybrid_model.HybridModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
