# coding: utf-8

"""
    Model Catalog

    This is MINT Model Catalog You can find out more about     Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: mosorio@isi.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mint_client
from mint_client.models.unit import Unit  # noqa: E501
from mint_client.rest import ApiException


class TestUnit(unittest.TestCase):
    """Unit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnit(self):
        """Test Unit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mint_client.models.unit.Unit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
