# coding: utf-8

"""
    Model Catalog

    This is the API of the  Software Description Ontology at [https://mintproject.github.io/Mint-ModelCatalog-Ontology/release/1.3.0/index-en.html](https://w3id.org/okn/o/sdm)  # noqa: E501

    OpenAPI spec version: v1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class GeoShape(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'elevation': 'list[str]',
        'latitude': 'list[str]',
        'description': 'list[str]',
        'box': 'list[str]',
        'id': 'str',
        'label': 'list[str]',
        'type': 'list[str]',
        'longitude': 'list[str]'
    }

    attribute_map = {
        'elevation': 'elevation',
        'latitude': 'latitude',
        'description': 'description',
        'box': 'box',
        'id': 'id',
        'label': 'label',
        'type': 'type',
        'longitude': 'longitude'
    }

    def __init__(self, elevation=None, latitude=None, description=None, box=None, id=None, label=None, type=None, longitude=None):  # noqa: E501
        """GeoShape - a model defined in OpenAPI"""  # noqa: E501

        self._elevation = None
        self._latitude = None
        self._description = None
        self._box = None
        self._id = None
        self._label = None
        self._type = None
        self._longitude = None
        self.discriminator = None

        if elevation is not None:
            self.elevation = elevation
        else:
            if hasattr(self, '_elevation'): del self._elevation
            if hasattr(self.attribute_map, 'elevation'): del self.attribute_map['elevation']
            if hasattr(self.openapi_types, 'elevation'): del self.openapi_types['elevation']
        if latitude is not None:
            self.latitude = latitude
        else:
            if hasattr(self, '_latitude'): del self._latitude
            if hasattr(self.attribute_map, 'latitude'): del self.attribute_map['latitude']
            if hasattr(self.openapi_types, 'latitude'): del self.openapi_types['latitude']
        if description is not None:
            self.description = description
        else:
            if hasattr(self, '_description'): del self._description
            if hasattr(self.attribute_map, 'description'): del self.attribute_map['description']
            if hasattr(self.openapi_types, 'description'): del self.openapi_types['description']
        if box is not None:
            self.box = box
        else:
            if hasattr(self, '_box'): del self._box
            if hasattr(self.attribute_map, 'box'): del self.attribute_map['box']
            if hasattr(self.openapi_types, 'box'): del self.openapi_types['box']
        if id is not None:
            self.id = id
        if label is not None:
            self.label = label
        else:
            if hasattr(self, '_label'): del self._label
            if hasattr(self.attribute_map, 'label'): del self.attribute_map['label']
            if hasattr(self.openapi_types, 'label'): del self.openapi_types['label']
        if type is not None:
            self.type = type
        else:
            if hasattr(self, '_type'): del self._type
            if hasattr(self.attribute_map, 'type'): del self.attribute_map['type']
            if hasattr(self.openapi_types, 'type'): del self.openapi_types['type']
        if longitude is not None:
            self.longitude = longitude
        else:
            if hasattr(self, '_longitude'): del self._longitude
            if hasattr(self.attribute_map, 'longitude'): del self.attribute_map['longitude']
            if hasattr(self.openapi_types, 'longitude'): del self.openapi_types['longitude']

    @property
    def elevation(self):
        """Gets the elevation of this GeoShape.  # noqa: E501


        :return: The elevation of this GeoShape.  # noqa: E501
        :rtype: list[str]
        """
        return self._elevation

    @elevation.setter
    def elevation(self, elevation):
        """Sets the elevation of this GeoShape.


        :param elevation: The elevation of this GeoShape.  # noqa: E501
        :type: list[str]
        """

        self._elevation = elevation

    @property
    def latitude(self):
        """Gets the latitude of this GeoShape.  # noqa: E501


        :return: The latitude of this GeoShape.  # noqa: E501
        :rtype: list[str]
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this GeoShape.


        :param latitude: The latitude of this GeoShape.  # noqa: E501
        :type: list[str]
        """

        self._latitude = latitude

    @property
    def description(self):
        """Gets the description of this GeoShape.  # noqa: E501


        :return: The description of this GeoShape.  # noqa: E501
        :rtype: list[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this GeoShape.


        :param description: The description of this GeoShape.  # noqa: E501
        :type: list[str]
        """

        self._description = description

    @property
    def box(self):
        """Gets the box of this GeoShape.  # noqa: E501


        :return: The box of this GeoShape.  # noqa: E501
        :rtype: list[str]
        """
        return self._box

    @box.setter
    def box(self, box):
        """Sets the box of this GeoShape.


        :param box: The box of this GeoShape.  # noqa: E501
        :type: list[str]
        """

        self._box = box

    @property
    def id(self):
        """Gets the id of this GeoShape.  # noqa: E501


        :return: The id of this GeoShape.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GeoShape.


        :param id: The id of this GeoShape.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this GeoShape.  # noqa: E501


        :return: The label of this GeoShape.  # noqa: E501
        :rtype: list[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this GeoShape.


        :param label: The label of this GeoShape.  # noqa: E501
        :type: list[str]
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this GeoShape.  # noqa: E501


        :return: The type of this GeoShape.  # noqa: E501
        :rtype: list[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this GeoShape.


        :param type: The type of this GeoShape.  # noqa: E501
        :type: list[str]
        """

        self._type = type

    @property
    def longitude(self):
        """Gets the longitude of this GeoShape.  # noqa: E501


        :return: The longitude of this GeoShape.  # noqa: E501
        :rtype: list[str]
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this GeoShape.


        :param longitude: The longitude of this GeoShape.  # noqa: E501
        :type: list[str]
        """

        self._longitude = longitude

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            if hasattr(self, attr):
                value = getattr(self, attr)
            else:
                continue                
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeoShape):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
