# coding: utf-8

"""
    Model Catalog

    This is MINT Model Catalog You can find out more about Model Catalog at [https://w3id.org/mint/modelCatalog/](https://w3id.org/mint/modelCatalog/)  # noqa: E501

    OpenAPI spec version: v1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PointBasedGrid(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'has_shape': 'list[str]',
        'has_dimension': 'list[str]',
        'id': 'str',
        'label': 'str',
        'type': 'list[str]',
        'has_spatial_resolution': 'list[str]',
        'has_coordinate_system': 'list[str]'
    }

    attribute_map = {
        'has_shape': 'hasShape',
        'has_dimension': 'hasDimension',
        'id': 'id',
        'label': 'label',
        'type': 'type',
        'has_spatial_resolution': 'hasSpatialResolution',
        'has_coordinate_system': 'hasCoordinateSystem'
    }

    def __init__(self, has_shape=None, has_dimension=None, id=None, label=None, type=None, has_spatial_resolution=None, has_coordinate_system=None):  # noqa: E501
        """PointBasedGrid - a model defined in OpenAPI"""  # noqa: E501

        self._has_shape = None
        self._has_dimension = None
        self._id = None
        self._label = None
        self._type = None
        self._has_spatial_resolution = None
        self._has_coordinate_system = None
        self.discriminator = None

        if has_shape is not None:
            self.has_shape = has_shape
        else:
            if hasattr(self, '_has_shape'): del self._has_shape
            if hasattr(self.attribute_map, 'has_shape'): del self.attribute_map['has_shape']
            if hasattr(self.openapi_types, 'has_shape'): del self.openapi_types['has_shape']
        if has_dimension is not None:
            self.has_dimension = has_dimension
        else:
            if hasattr(self, '_has_dimension'): del self._has_dimension
            if hasattr(self.attribute_map, 'has_dimension'): del self.attribute_map['has_dimension']
            if hasattr(self.openapi_types, 'has_dimension'): del self.openapi_types['has_dimension']
        if id is not None:
            self.id = id
        if label is not None:
            self.label = label
        else:
            if hasattr(self, '_label'): del self._label
            if hasattr(self.attribute_map, 'label'): del self.attribute_map['label']
            if hasattr(self.openapi_types, 'label'): del self.openapi_types['label']
        if type is not None:
            self.type = type
        else:
            if hasattr(self, '_type'): del self._type
            if hasattr(self.attribute_map, 'type'): del self.attribute_map['type']
            if hasattr(self.openapi_types, 'type'): del self.openapi_types['type']
        if has_spatial_resolution is not None:
            self.has_spatial_resolution = has_spatial_resolution
        else:
            if hasattr(self, '_has_spatial_resolution'): del self._has_spatial_resolution
            if hasattr(self.attribute_map, 'has_spatial_resolution'): del self.attribute_map['has_spatial_resolution']
            if hasattr(self.openapi_types, 'has_spatial_resolution'): del self.openapi_types['has_spatial_resolution']
        if has_coordinate_system is not None:
            self.has_coordinate_system = has_coordinate_system
        else:
            if hasattr(self, '_has_coordinate_system'): del self._has_coordinate_system
            if hasattr(self.attribute_map, 'has_coordinate_system'): del self.attribute_map['has_coordinate_system']
            if hasattr(self.openapi_types, 'has_coordinate_system'): del self.openapi_types['has_coordinate_system']

    @property
    def has_shape(self):
        """Gets the has_shape of this PointBasedGrid.  # noqa: E501


        :return: The has_shape of this PointBasedGrid.  # noqa: E501
        :rtype: list[str]
        """
        return self._has_shape

    @has_shape.setter
    def has_shape(self, has_shape):
        """Sets the has_shape of this PointBasedGrid.


        :param has_shape: The has_shape of this PointBasedGrid.  # noqa: E501
        :type: list[str]
        """

        self._has_shape = has_shape

    @property
    def has_dimension(self):
        """Gets the has_dimension of this PointBasedGrid.  # noqa: E501


        :return: The has_dimension of this PointBasedGrid.  # noqa: E501
        :rtype: list[str]
        """
        return self._has_dimension

    @has_dimension.setter
    def has_dimension(self, has_dimension):
        """Sets the has_dimension of this PointBasedGrid.


        :param has_dimension: The has_dimension of this PointBasedGrid.  # noqa: E501
        :type: list[str]
        """

        self._has_dimension = has_dimension

    @property
    def id(self):
        """Gets the id of this PointBasedGrid.  # noqa: E501


        :return: The id of this PointBasedGrid.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PointBasedGrid.


        :param id: The id of this PointBasedGrid.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this PointBasedGrid.  # noqa: E501


        :return: The label of this PointBasedGrid.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this PointBasedGrid.


        :param label: The label of this PointBasedGrid.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this PointBasedGrid.  # noqa: E501


        :return: The type of this PointBasedGrid.  # noqa: E501
        :rtype: list[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PointBasedGrid.


        :param type: The type of this PointBasedGrid.  # noqa: E501
        :type: list[str]
        """

        self._type = type

    @property
    def has_spatial_resolution(self):
        """Gets the has_spatial_resolution of this PointBasedGrid.  # noqa: E501


        :return: The has_spatial_resolution of this PointBasedGrid.  # noqa: E501
        :rtype: list[str]
        """
        return self._has_spatial_resolution

    @has_spatial_resolution.setter
    def has_spatial_resolution(self, has_spatial_resolution):
        """Sets the has_spatial_resolution of this PointBasedGrid.


        :param has_spatial_resolution: The has_spatial_resolution of this PointBasedGrid.  # noqa: E501
        :type: list[str]
        """

        self._has_spatial_resolution = has_spatial_resolution

    @property
    def has_coordinate_system(self):
        """Gets the has_coordinate_system of this PointBasedGrid.  # noqa: E501


        :return: The has_coordinate_system of this PointBasedGrid.  # noqa: E501
        :rtype: list[str]
        """
        return self._has_coordinate_system

    @has_coordinate_system.setter
    def has_coordinate_system(self, has_coordinate_system):
        """Sets the has_coordinate_system of this PointBasedGrid.


        :param has_coordinate_system: The has_coordinate_system of this PointBasedGrid.  # noqa: E501
        :type: list[str]
        """

        self._has_coordinate_system = has_coordinate_system

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            if hasattr(self, attr):
                value = getattr(self, attr)
            else:
                continue                
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PointBasedGrid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
