# coding: utf-8

"""
    Model Catalog

    This is the API of the  Software Description Ontology at [https://mintproject.github.io/Mint-ModelCatalog-Ontology/release/1.3.0/index-en.html](https://w3id.org/okn/o/sdm)  # noqa: E501

    OpenAPI spec version: v1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SampleCollection(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'data_catalog_identifier': 'list[str]',
        'has_part': 'list[SampleResource]',
        'description': 'list[str]',
        'id': 'str',
        'label': 'list[str]',
        'type': 'list[str]',
        'value': 'list[object]'
    }

    attribute_map = {
        'data_catalog_identifier': 'dataCatalogIdentifier',
        'has_part': 'hasPart',
        'description': 'description',
        'id': 'id',
        'label': 'label',
        'type': 'type',
        'value': 'value'
    }

    def __init__(self, data_catalog_identifier=None, has_part=None, description=None, id=None, label=None, type=None, value=None):  # noqa: E501
        """SampleCollection - a model defined in OpenAPI"""  # noqa: E501

        self._data_catalog_identifier = None
        self._has_part = None
        self._description = None
        self._id = None
        self._label = None
        self._type = None
        self._value = None
        self.discriminator = None

        if data_catalog_identifier is not None:
            self.data_catalog_identifier = data_catalog_identifier
        else:
            if hasattr(self, '_data_catalog_identifier'): del self._data_catalog_identifier
            if hasattr(self.attribute_map, 'data_catalog_identifier'): del self.attribute_map['data_catalog_identifier']
            if hasattr(self.openapi_types, 'data_catalog_identifier'): del self.openapi_types['data_catalog_identifier']
        if has_part is not None:
            self.has_part = has_part
        else:
            if hasattr(self, '_has_part'): del self._has_part
            if hasattr(self.attribute_map, 'has_part'): del self.attribute_map['has_part']
            if hasattr(self.openapi_types, 'has_part'): del self.openapi_types['has_part']
        if description is not None:
            self.description = description
        else:
            if hasattr(self, '_description'): del self._description
            if hasattr(self.attribute_map, 'description'): del self.attribute_map['description']
            if hasattr(self.openapi_types, 'description'): del self.openapi_types['description']
        if id is not None:
            self.id = id
        if label is not None:
            self.label = label
        else:
            if hasattr(self, '_label'): del self._label
            if hasattr(self.attribute_map, 'label'): del self.attribute_map['label']
            if hasattr(self.openapi_types, 'label'): del self.openapi_types['label']
        if type is not None:
            self.type = type
        else:
            if hasattr(self, '_type'): del self._type
            if hasattr(self.attribute_map, 'type'): del self.attribute_map['type']
            if hasattr(self.openapi_types, 'type'): del self.openapi_types['type']
        if value is not None:
            self.value = value
        else:
            if hasattr(self, '_value'): del self._value
            if hasattr(self.attribute_map, 'value'): del self.attribute_map['value']
            if hasattr(self.openapi_types, 'value'): del self.openapi_types['value']

    @property
    def data_catalog_identifier(self):
        """Gets the data_catalog_identifier of this SampleCollection.  # noqa: E501


        :return: The data_catalog_identifier of this SampleCollection.  # noqa: E501
        :rtype: list[str]
        """
        return self._data_catalog_identifier

    @data_catalog_identifier.setter
    def data_catalog_identifier(self, data_catalog_identifier):
        """Sets the data_catalog_identifier of this SampleCollection.


        :param data_catalog_identifier: The data_catalog_identifier of this SampleCollection.  # noqa: E501
        :type: list[str]
        """

        self._data_catalog_identifier = data_catalog_identifier

    @property
    def has_part(self):
        """Gets the has_part of this SampleCollection.  # noqa: E501


        :return: The has_part of this SampleCollection.  # noqa: E501
        :rtype: list[SampleResource]
        """
        return self._has_part

    @has_part.setter
    def has_part(self, has_part):
        """Sets the has_part of this SampleCollection.


        :param has_part: The has_part of this SampleCollection.  # noqa: E501
        :type: list[SampleResource]
        """

        self._has_part = has_part

    @property
    def description(self):
        """Gets the description of this SampleCollection.  # noqa: E501


        :return: The description of this SampleCollection.  # noqa: E501
        :rtype: list[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SampleCollection.


        :param description: The description of this SampleCollection.  # noqa: E501
        :type: list[str]
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this SampleCollection.  # noqa: E501


        :return: The id of this SampleCollection.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SampleCollection.


        :param id: The id of this SampleCollection.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this SampleCollection.  # noqa: E501


        :return: The label of this SampleCollection.  # noqa: E501
        :rtype: list[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this SampleCollection.


        :param label: The label of this SampleCollection.  # noqa: E501
        :type: list[str]
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this SampleCollection.  # noqa: E501


        :return: The type of this SampleCollection.  # noqa: E501
        :rtype: list[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SampleCollection.


        :param type: The type of this SampleCollection.  # noqa: E501
        :type: list[str]
        """

        self._type = type

    @property
    def value(self):
        """Gets the value of this SampleCollection.  # noqa: E501


        :return: The value of this SampleCollection.  # noqa: E501
        :rtype: list[object]
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this SampleCollection.


        :param value: The value of this SampleCollection.  # noqa: E501
        :type: list[object]
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            if hasattr(self, attr):
                value = getattr(self, attr)
            else:
                continue                
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SampleCollection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
