# coding: utf-8

"""
    Model Catalog

    This is the API of the Software Description Ontology at [https://w3id.org/okn/o/sdm](https://w3id.org/okn/o/sdm)  # noqa: E501

    The version of the OpenAPI document: v1.7.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class TimeInterval(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'list[str]',
        'id': 'str',
        'interval_unit': 'list[Unit]',
        'interval_value': 'list[object]',
        'label': 'list[str]',
        'type': 'list[str]'
    }

    attribute_map = {
        'description': 'description',
        'id': 'id',
        'interval_unit': 'intervalUnit',
        'interval_value': 'intervalValue',
        'label': 'label',
        'type': 'type'
    }

    def __init__(self, description=None, id=None, interval_unit=None, interval_value=None, label=None, type=None):  # noqa: E501
        """TimeInterval - a model defined in OpenAPI"""  # noqa: E501

        self._description = None
        self._id = None
        self._interval_unit = None
        self._interval_value = None
        self._label = None
        self._type = None
        self.discriminator = None

        self.description = description
        if id is not None:
            self.id = id
        self.interval_unit = interval_unit
        self.interval_value = interval_value
        self.label = label
        self.type = type

    @property
    def description(self):
        """Gets the description of this TimeInterval.  # noqa: E501

        small description  # noqa: E501

        :return: The description of this TimeInterval.  # noqa: E501
        :rtype: list[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TimeInterval.

        small description  # noqa: E501

        :param description: The description of this TimeInterval.  # noqa: E501
        :type: list[str]
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this TimeInterval.  # noqa: E501

        identifier  # noqa: E501

        :return: The id of this TimeInterval.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TimeInterval.

        identifier  # noqa: E501

        :param id: The id of this TimeInterval.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def interval_unit(self):
        """Gets the interval_unit of this TimeInterval.  # noqa: E501

        Unit used in an interval (e.g., month)  # noqa: E501

        :return: The interval_unit of this TimeInterval.  # noqa: E501
        :rtype: list[Unit]
        """
        return self._interval_unit

    @interval_unit.setter
    def interval_unit(self, interval_unit):
        """Sets the interval_unit of this TimeInterval.

        Unit used in an interval (e.g., month)  # noqa: E501

        :param interval_unit: The interval_unit of this TimeInterval.  # noqa: E501
        :type: list[Unit]
        """

        self._interval_unit = interval_unit

    @property
    def interval_value(self):
        """Gets the interval_value of this TimeInterval.  # noqa: E501

        Value used in the time interval of a model (e.g., 1 month, 5 days, 'harvest cycle')  # noqa: E501

        :return: The interval_value of this TimeInterval.  # noqa: E501
        :rtype: list[object]
        """
        return self._interval_value

    @interval_value.setter
    def interval_value(self, interval_value):
        """Sets the interval_value of this TimeInterval.

        Value used in the time interval of a model (e.g., 1 month, 5 days, 'harvest cycle')  # noqa: E501

        :param interval_value: The interval_value of this TimeInterval.  # noqa: E501
        :type: list[object]
        """

        self._interval_value = interval_value

    @property
    def label(self):
        """Gets the label of this TimeInterval.  # noqa: E501

        short description of the resource  # noqa: E501

        :return: The label of this TimeInterval.  # noqa: E501
        :rtype: list[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this TimeInterval.

        short description of the resource  # noqa: E501

        :param label: The label of this TimeInterval.  # noqa: E501
        :type: list[str]
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this TimeInterval.  # noqa: E501

        type of the resource  # noqa: E501

        :return: The type of this TimeInterval.  # noqa: E501
        :rtype: list[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TimeInterval.

        type of the resource  # noqa: E501

        :param type: The type of this TimeInterval.  # noqa: E501
        :type: list[str]
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeInterval):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
